version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/
    steps:
      - checkout
      - run: npm install
      - run:
          name: HTML syntax check
          command: npx htmlhint ./**/*.html
      - run:
          name: JavaScript syntax check
          command: npx eslint ./**/*.js
      - run:
          name: CSS syntax check
          command: npx stylelint ./**/*.css

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
